[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
mint_program = "3U9SD3UEX34UT67w52eEazQk4kSK36eQ75ewpkfky7B7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bash scripts/run-tests.sh"
